### ISSUE TITLE
What should happen if the viewport-defining element is an inline?

### ISSUE THREAD

**Issue by ojanvafai** [w3c/IntersectionObserver#13]
Related to issue #10, what should happen if the viewport-defining element is an inline?

I see a couple options I'd be happy with:
1. Use the bounding box of the inline ancestor.
2. Stop delivering callbacks and queueing change records.

This is not a use-case we need to support, so whatever is simplest.

**Comment by esprehn** [comment]
Discussed with @ojanvafai lets do everything in terms of the bounding client rect. So it's as if we use getBoundingClientRect() on both the root and on the target for observations.

**Comment by ojanvafai** [comment]
@szager-chromium points out that for blocks, we should be using the content box and for inlines we should use the bounding client rect. Not sure what the right specese for this is.

@tabatkins, any suggestions?

**Comment by tabatkins** [comment]
Boxes don't exist, they're a spec abstraction to help talk about styling.  At layout time you only have fragments, of which an element can generate 0 or more of.  So you can't talk about content boxes; your choices are:

* talk about the fragments individually
* talk about the "glued together pre-fragmentation area" (tho that's not *really* well-defined in CSS, since the fragments are allowed to be different widths when paging or doing Regions, or different heights when linebreaking an inline, so you have to limit yourself to discussing things like "progression along the breaking axis", which is well-defined)
* talk about the bounding rect of the fragments

In this case, you probably want the bounding rect of the content box fragments.  That should work for all elements, I think.  It'll handle both inlines broken across lines, and blocks broken across columns, in a reasonable way.

**Comment by szager-chromium** [comment]
Tab, I tremble before your spec-ese, but the intention was that if root is a container element, then we should be checking intersection against its content box as defined thus:

https://drafts.csswg.org/css2/box.html#content-edge

How do we express that?

**Comment by tabatkins** [comment]
With one of the three options I gave, depending on what you're looking for. ^_^

But actually, looking back at the explainer some more, you don't want any of those.  You want the scroll viewport of the element (or of the screen).  That's the thing that you're intersecting with the child's rectangle to figure out thresholds and visibility.

In that case, just talk about scroll viewport.  It's kinda handwaved in <https://drafts.csswg.org/css-scroll-snap/> right now, but we'll be defining it better soonish.  Elements that don't have a scroll viewport thus can't deliver notifications at all. In other words, go with your options 2 in the OP, and don't deliver anything while the element is in a state that doesn't support a scroll viewport.

---

Now, for the *observed* element (the child), you want the third option in my list.  You can't use the second option, because you want a rectangle.  It's not worth the complexity of adding the ability to observe multiple fragments separately, so the first option is out.  So the third one is what you want - probably the bounding rect of the element's border-box fragments, after each has been grown by the rootMargin.

**Comment by szager-chromium** [comment]
Since the spec now describes everything in terms of getBoundingClientRect, I think this issue is moot.  I'm going to close it, please reopen if think there's more spec work to do.
