### ISSUE TITLE
`IntersectionCallback` needs better explaination or naming

### ISSUE THREAD

**Issue by pedi** [w3c/IntersectionObserver#153]
It's not quite obvious from the README that this `IntersectionCallback` will actually be fired whenever the intersection condition changed. 

For example, if threshold is 0.3, this callback will be called for both intersection part becomes above and below 0.3. 

It might be easily interpolated as `IntersectionCallback` will only be called if the threshold condition is met. Or at least there's no way to confirm what the exact behavior is except experimenting around with it. 

`IntersectionCallback` is better called `IntersectionChangeCallback` or we can add better documentation for this part. 

Just my two cents.

**Comment by szager-chromium** [comment]
I'm open to ways we can explain this better; please let me know how we can do that.

Currently, the explainer doc says:

"The callback includes change records for all elements that have crossed the threshold of the root element since the last callback. Conceptually, this gives you a rectangle (based at the root element) that calls a callback whenever a given point in each element crosses the threshold."

The spec says:

"Callback will be invoked when intersectionRect’s area changes from greater than or equal to any threshold to less than that threshold, and vice versa."

... and the text of  then "Run the Update Intersection Observations Steps" is very explicit about how thresholds are treated (see steps 7-12):

https://wicg.github.io/IntersectionObserver/#update-intersection-observations-algo

**Comment by pedi** [comment]
Personally I feel **all elements that have crossed the threshold** is a bit subtle here.
While "Callback will be invoked when intersectionRect’s area changes from greater than or equal to any threshold to less than that threshold, **and vice versa.**" is actually much clearer
