### ISSUE TITLE
Handles target elements not yet added to the DOM test failing in Chrome 60

### ISSUE THREAD

**Issue by JakeChampion** [w3c/IntersectionObserver#237]
Chrome 60 looks to be seeing 4 elements instead of 5. `AssertionError: 4 == 5`.

https://github.com/WICG/IntersectionObserver/blob/56ad58fd4487d75f7569b7b2e6311264157f9eed/polyfill/intersection-observer-test.js#L629-L704

**Comment by JakeChampion** [comment]
This is also failing in Chrome Canary Version 62.0.3188.0

**Comment by philipwalton** [comment]
@szager-chromium it looks like Chrome's implementation doesn't trigger the callback if the root element itself is removed from the DOM. I filed [crbug.com/759890](https://bugs.chromium.org/p/chromium/issues/detail?id=759890) since I assume this is a bug, but let me know if you think it's not.
 
BTW, the callback *is* fired in Firefox and Edge.

**Comment by JakeChampion** [comment]
Thanks for filing the bug @philipwalton I wasn't sure if it was a bug or not. I just saw the tests failing on polyfill.io when I configured it to test the browsers without using a polyfill.
