### ISSUE TITLE
MutationObserver on Safari 10.0.3 causes browser to freeze and CPU usage to spike to 100%

### ISSUE THREAD

**Issue by bpossolo** [w3c/IntersectionObserver#261]
The MutationObserver activated by [this block of code](https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L270) causes my Safari browser (10.0.3) to grind to a standstill.

I would like to submit a PR to make the usage of the MutationObserver optional.
It would look something like this:

```
IntersectionObserver.prototype.USE_MUTATION_OBSERVER = true;
...
if (this.USE_MUTATION_OBSERVER && 'MutationObserver' in window) {
 // existing code that registers MutationObserver
}
```

usage:
```
var io = new IntersectionObserver(...);
io.USE_MUTATION_OBSERVER = false;
```

Any feedback is welcome.

**Comment by philipwalton** [comment]
I'm not opposed to something like this since I'm sure there are sites (e.g. content sites) where the DOM rarely changes and thus MO use isn't really needed, but I'm also curious to know why this is happening for you.

I've not previously heard that MO is slow on Safari, so I'm wondering if this is specific to your use case.

**Comment by JSteunou** [comment]
This issue can now be closed :)

Thank you everyone involved!

**Comment by dackmin** [comment]
I know this issue was closed a while back, but I am still experiencing this with Safari 11.1, even with `USE_MUTATION_OBSERVER` set to `false` 🤷‍♂️  

@bpossolo @JSteunou do you remember doing anything else back then not to make Safari and/or your CPU suffocate when using the polyfill ? Beside not using it 😄
