### ISSUE TITLE
Does the polyfill support iframes?

### ISSUE THREAD

**Issue by canscaw28** [w3c/IntersectionObserver#297]
I would like use the polyfill within an iframe to detect if the iframe itself has been intersected with the host's viewport. Is this supported? Thanks!

**Comment by szager-chromium** [comment]
If the iframe is cross-origin, then no, it will not work. I *think* same-origin iframes are supported, but not 100% sure.

**Comment by richardraviis** [comment]
I am also facing issue with the cross origin iframe. Can someone please confirm if the polyfill works on cross origin iframe.

**Comment by philipwalton** [comment]
The polyfill does not currently work on either same-origin or cross-origin iframes.

While it *could* work on same-origin iframes, supporting that would add a significant amount of extra code to the size of the polyfill, and I originally I wasn't sure how common of a use case it would be.

The amount and complexity of code required to support iframes is large because you have to know the x/y coordinates of the current frame you're in with respect to the top window. While that in and of itself isn't too bad, where it gets really tricky is handling cases where the frame is nested within one or more parent frames and those frames may be moving/scrolling/transitioning their positions, thus affecting your frame's x/y position inside the top frame's window.

My sense is most iframe use cases are cross-origin anyway, so unless I hear a lot of people asking for this feature, I'd prefer to keep the implementation minimal.

**Comment by dackmin** [comment]
@philipwalton you should at least mention it in the polyfill README, as the current browser implementation supports cross-origin iframes correctly (at least on Firefox & Chrome).
I spent a lot of time wondering why it wasn't working on Safari until I noticed Safari was using the polyfill.

**Comment by philipwalton** [comment]
I added a [limitations](https://github.com/w3c/IntersectionObserver/tree/master/polyfill#limitations) section where I address this and the proposed v2 changes (which the polyfill will also not be able to support).
