### ISSUE TITLE
IntersectionObserver doesn't fire if a resize causes it to be visible on screen

### ISSUE THREAD

**Issue by matthew-dean** [w3c/IntersectionObserver#311]
We have components that mount / unmount via React on resize and we're using the intersection observer to show parts of those components if visible.

However, if we mount those components (add them to the DOM) and add an IntersectionObserver, the IntersectionObserver doesn't fire. However, if you scroll up and back down to the element, then it fires.

**Comment by tedw** [comment]
Anyone found a good solution for this, other writing additional code to check the positions on window resize?

**Comment by miketaylr** [comment]
I think this could be covered by the proposal in https://github.com/w3c/IntersectionObserver/issues/471 - let's close here in favor of that. Thanks.

**Comment by 75th** [comment]
That issue seems to be about making the computer display, rather than the viewport or a particular element, the IntersectionObserver's root. How on Earth does that address the problem of viewport resizing not triggering the IntersectionObserver's callback? I don't see how they're related or how the former will help with the problem reported in this issue.

**Comment by AkimaLunar** [comment]
Second what @75th is saying, #471 is unrelated to viewport resizing not triggering the IntersectionObserver’s callback. Could we reopen the issue?

Is there a reason why IntersectionObserver doesn’t fire on resize? Is there a performance issue with that or was it just not in the spec?
