### ISSUE TITLE
Polyfill : Add option to force use of polyfill incase of broken browser implementations

### ISSUE THREAD

**Issue by rjgotten** [w3c/IntersectionObserver#405]
The polyfill really needs an option to force replace broken browser implementations.

Case in point:
The native implementation of `IntersectionObserver` offered in MSEdge 15 is broken for anything but the most basic use cases, as it flat out ignores `rootMargin` when `root` is `null` - i.e. the document viewport should be used.

Right now there is no way to force use of the polyfill, other than using the `delete` operator to remove the native implementation from the window wholesale, before the polyfill is loaded. Far from ideal.

**Comment by miketaylr** [comment]
I think the better solution would be to file bugs agains the browser vendor's native implementations instead. 

The preferred end-state is that the polyfill becomes un-needed over time (and we may be pretty close to that in 2022). 
Given that there is already a workaround (`delete`, as you mentioned), and Edge has since shipped a better implementation, I think we should close this as wontfix. But thank you for the issue.
