### ISSUE TITLE
Add Internationalization Considerations section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/IntersectionObserver#415]
There may or may not be any internationalization concerns with the spec, but we should make sure to have an "Internationalization Considerations" section stating that we've taken i18n into consideration. Of course, if there are things that should be considered, we should add them there :)

We will also ask the i18n WG to review the spec to see if they have any feedback for us.

This is part of w3c/webappswg#25

**Comment by marcoscaceres** [comment]
@LJWatson, I set the i18n-tracker label on this, but I'm unsure what the next steps are to have the l18n folks look at the spec? Do we need to ping them directly though their mailing list to request review?

**Comment by himorin** [comment]
for formal horizontal review process including i18n, please check at https://w3c.github.io/documentreview/, post-FPWD or pre-CR might be the closest one?

**Comment by aphillips** [comment]
@marcoscaceres `i18n-tracker` causes us to come look at a specific issue. @himorin pointed out the horizontal review instructions. For I18N, the horizontal review is kicked off by adding an issue [here](https://github.com/w3c/i18n-request/issues) (we have a nice template to fill in 😉)

Regarding this specific issue (and speaking as an individual), I'm not a fan of the "I18N penalty box" in a spec. When there are internationalization issues we generally deal with them in-line, rather than splitting them off to be addressed separately. While I like and appreciate that this WG is thinking actively about I18N, "we don't need the publicity" and I think you'd be better off omitting this section unless/until there is something material that needs to be documented (and which doesn't fit into the flow of your specification).

**Comment by marcoscaceres** [comment]
I too agree and prefer the inline approach, tbh. I'll also note that other folks prefer having their own box (e.g., privacy/sec) - but it's great to know we don't need to include one for i18n.

**Comment by szager-chromium** [comment]
I can't think of anything about IntersectionObserver that would raise internationalization concerns, so based on the conversation so far, I'm going to close this.

If a specific internationalization issue comes up, please create a new issue.
