### ISSUE TITLE
rootMargin definition uses outdated HTML Standard definition

### ISSUE THREAD

**Issue by domfarolino** [w3c/IntersectionObserver#429]
https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-rootmargin:

> Offsets applied to the root intersection rectangle, effectively growing or shrinking the box that is used to calculate intersections. Note that rootMargin is only applied for targets which belong to the same unit of related similar-origin browsing contexts as the intersection root.

The HTML Standard mentions that the [unit-of-related-similar-origin-browsing-contexts](https://html.spec.whatwg.org/multipage/browsers.html#unit-of-related-similar-origin-browsing-contexts) definition has been removed. I'm not sure if there is an equivalent definition that this spec could reference instead, maybe @domenic would know?

**Comment by domenic** [comment]
It's a little hard to figure out what this was originally trying to say, since DOM elements never "belonged to" URSOBCs. In particular I'm wondering if this is trying to translate any implementation-specific notions, such as process, or thread, into spec language? Which could be problematic.

Anyway, my guess as to a reasonable replacement would be the element's [relevant agent](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-agent), which would contain all DOM elements which can access others synchronously, or could potentially do so after `document.domain` is set.

**Comment by szager-chromium** [comment]
"Unit of related similar origin browsing contexts" referred to the connected graph of nested browsing contexts that all belong to the same origin. I think *browsing context scope origin* can be used instead:

https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-group
