### ISSUE TITLE
Move section 3.3.1 to the HTML5 spec

### ISSUE THREAD

**Issue by szager-chromium** [w3c/IntersectionObserver#94]
Should be added here:

http://rawgit.com/WICG/IntersectionObserver/master/index.html#event-loop

**Comment by domenic** [comment]
I've run into several issues and questions while working on this that I need some help clearing up:

- "Let unit be the unit of related similar-origin browsing contexts for loop." There is no unique such unit; as the HTML spec says, "There is also at most one event loop per unit of related similar-origin browsing contexts (**though several units of related similar-origin browsing contexts can have a shared event loop**)."
   - It seems like you are essentially trying to get the list of Documents associated with the event loop in question. If that's the case, you should probably just use the documents stored in the _docs_ variable in https://html.spec.whatwg.org/#processing-model-8 step 2.
  - It's unclear to me whether you want to update intersection observers for documents that the browser does not want to update (e.g. offscreen third party iframes, or inactive tabs, or documents that have been updated already in the last 16.666 milliseconds). If you do, then these steps should probably be run using the documents from step 2. Otherwise, you should use the documents from step 4 onward (steps 3 and 4 filter out documents that the browser does not want to update). If I had to guess, you want to use the post-filtering documents, since then the browser can avoid doing the getBoundingClientRect()-like computations for those inactive tabs/etc., and isn't forced to do it every turn around the event loop, but instead only every frame.
  - HTML also restricts all the other rendering-update things to only work on fully active Documents. That seems important---disconnected documents created with `document.implementation.createHTMLDocument()`, or documents from navigated-away iframes, should probably not get their intersection observers run.
- The section you link to says to do this at step 12. I think it should instead be step 11---after animation frame callbacks, but before actually painting on the screen. That's where everything else seems to go. Maybe it doesn't make a difference, since you are queuing the callbacks anyway.
- The algorithm operates on an entire event loop, whereas all similar algorithms operate on documents. This lets HTML apply the same inter-document ordering for different specs, which I think is better.

So, I think the correct changes are as follows:

- "run the update intersection observations steps" should be updated to take in a single document and a timestamp.
- Then, HTML can insert as step 11, "For each fully active Document in _docs_, run the update intersection observations steps for that Document, passing in _now_ as the timestamp."

If I am getting something wrong, and e.g. you want to operate on all documents (inactive, disconnected, every time around the event loop not just every frame, ...) we'll need to work out something more complicated. In that case maybe it's not even part of "update the rendering" at all?

**Comment by szager-chromium** [comment]
I think you're right about using the loop's list of documents; Ojan, Michael, thoughts?

As for whether "inactive" docs will be processed: I think this existing preceding step in the event loop processing model should cover it:

"If there are top-level browsing contexts B that the user agent believes would not benefit from having their rendering updated at this time, then remove from docs all Document objects whose browsing context's top-level browsing context is in B."

That's step 7.3 from https://html.spec.whatwg.org/#processing-model-8

**Comment by domenic** [comment]
> As for whether "inactive" docs will be processed: I think this existing preceding step in the event loop processing model should cover it:

Right. My question was whether the intention was to avoid this filtering (like the current algorithm at http://rawgit.com/WICG/IntersectionObserver/master/index.html#run-the-update-intersection-observations-steps does) or if that was accidental. Sounds like it's accidental, which is great.

**Comment by mpb** [comment]
SGTM, and I agree with the comment about accidental filtering.

**Comment by domenic** [comment]
Great. Let me know when "run the update intersection observations steps" is changed to accept a single document instead of an event loop and I'll send my HTML PR.

**Comment by mpb** [comment]
PTAL at #106

**Comment by KenjiBaheux** [comment]
Pull request #106 got merged.
Is there anything else remaining here or can we close?

**Comment by ojanvafai** [comment]
Section 3.4 needs to be rewritten to point to the HTML spec now that the actual steps are moved into the HTML spec. I think we still want a pointer in this spec so that vendors implementing it get the timing right.

**Comment by miketaylr** [comment]
It looks like this did get done at some point.

**Comment by miketaylr** [comment]
What about https://w3c.github.io/IntersectionObserver/#pending-initial-observation - do we want to move that to HTML as well @szager-chromium @domenic?
